/*
 * GENERATED by scripts/gen-templates.js. Do not edit — regenerate with:
 *
 *     npx tsc && node scripts/gen-templates.js
 *
 * The project template table, from projectManager.ts's getTemplates().
 * 6 templates, 22 files, 37460 bytes of content.
 *
 * Proven byte-for-byte against the TypeScript by core/test/templates-parity.js.
 */

#ifndef NEXIA_TEMPLATES_H
#define NEXIA_TEMPLATES_H

/* For NULL: templates.c is nothing but a table, and the empty slots in it are
 * NULL. Included here rather than there so anything that includes this header
 * gets a table it can actually name. */
#include <stddef.h>

typedef struct { const char *path; const char *content; } nx_tpl_file;
typedef struct { const char *from; const char *to; } nx_tpl_sdk;
typedef struct { const char *name; const char **libraries; int nlibraries; } nx_tpl_cfg;

typedef struct {
    const char *id, *name, *description, *icon;
    const nx_tpl_file *files;      int nfiles;
    const nx_tpl_sdk  *sdk_files;  int nsdk_files;
    const char *type, *template_id;
    const char **source_files;      int nsource_files;
    const char **defines;           int ndefines;
    const char **libraries;         int nlibraries;
    const char **include_dirs;      int ninclude_dirs;
    const nx_tpl_cfg *configurations; int nconfigurations;
    /* NULL when the template has no xuiContent. */
    const char *xui_package;
    const char **xui_scenes;        int nxui_scenes;
    const char **xui_copy;          int nxui_copy;
} nx_template;

extern const nx_template NX_TEMPLATES[];
extern const int NX_TEMPLATE_COUNT;

#endif
