/*
 * templates.h — GENERATED by scripts/gen-templates.js. Do not edit.
 *
 * The project templates' file contents, lifted verbatim out of
 * src/main/projectManager.ts. Regenerate with:
 *
 *     node scripts/gen-templates.js
 *
 * 8 templates, 13 lines of content.
 */

#ifndef NEXIA_TEMPLATES_H
#define NEXIA_TEMPLATES_H

extern const char TPL_STDAFX_H[];
extern const char TPL_STDAFX_CPP[];
extern const char TPL_XUI_MEDIA_README[];
extern const char TPL_DLL_HEADER[];
extern const char TPL_XBOX_APP_MAIN[];
extern const char TPL_HELLO_MAIN[];
extern const char TPL_XUI_MAIN[];
extern const char TPL_XBLA_MAIN[];

#endif
