/**
 * gen-version.js — Generate installer/version_generated.h from package.json
 * Usage: node scripts/gen-version.js
 *
 * The native installer displays its version and writes it to Add/Remove
 * Programs. That version used to be a hand-maintained #define, which drifted:
 * v2.2.2 shipped a wizard reading "v2.1.0" and registered 2.1.0.
 *
 * The header is only rewritten when the version actually changes, so an
 * unchanged build keeps its mtime and stays cached.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const { version } = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

if (!/^\d+\.\d+\.\d+/.test(version)) {
    console.error(`[X] package.json version "${version}" is not X.Y.Z`);
    process.exit(1);
}

const out = path.join(root, 'installer', 'version_generated.h');
const body = `/* GENERATED by scripts/gen-version.js from package.json — do not edit.
 * Edit package.json's "version" instead; this file is rewritten on every build.
 */
#ifndef NXI_VERSION_GENERATED_H
#define NXI_VERSION_GENERATED_H

#define NXI_APP_VERSION L"${version}"

#endif
`;

let prev = null;
try { prev = fs.readFileSync(out, 'utf8'); } catch { /* first run */ }

if (prev === body) {
    console.log(`   [OK] Version unchanged (${version})`);
} else {
    fs.writeFileSync(out, body);
    console.log(`   [OK] Version header generated: ${version}`);
}
